#!/bin/sh

. $(dirname $0)/env.sh

SCALA_VERSION=2.8.2-SNAPSHOT
#THIS NEEDS TO BE UPDATED ONCE WE HAVE SNAPSHOTS
SCALA_PRECOMPILED=2_8_2-SNAPSHOT
SBT_SCALA_VERSION=2.8.1
SBT_VERSION=0.10.1-SNAPSHOT
SBINARY_VERSION=0.4.0

set_version ${SCALA_VERSION} ${SBT_VERSION} ${SBINARY_VERSION} ${SCALA_PRECOMPILED} ${SBT_SCALA_VERSION}

PROFILE="-P sbt-2.8,default"

build $*
