#!/bin/sh

. $(dirname $0)/env.sh

SCALA_VERSION=2.9.1-SNAPSHOT
#THIS NEEDS TO BE UPDATED ONCE WE HAVE SNAPSHOTS
SCALA_PRECOMPILED=2_9_1-SNAPSHOT
SBT_SCALA_VERSION=2.9.0-1
SBINARY_VERSION=0.4.0

set_version ${SCALA_VERSION}

PROFILE="-P sbt-2.9,default"

build $*
